local addonName, addonTable = ...

local craftingData = {
	{ min = 1, max = 18, craft = { "Ivory Ink" }, recipe = { "1x Alabaster Pigment" } },
	{ min = 19, max = 34, craft = { "Scroll of Stamina" }, recipe = { "1x Ivory Ink, 1x Light Parchment" } },
	{ min = 35, max = 52, craft = { "Moonglow Ink" }, recipe = { "2x Alabaster Pigment" } },
	{ min = 53, max = 74, craft = { "Armor Vellum" }, recipe = { "1x Moonglow Ink, 2x Light Parchment" } },
	{ min = 75, max = 79, craft = { "Midnight Ink" }, recipe = { "2x Dusky Pigment" } },
	{
		min = 80,
		max = 84,
		craft = {
			"Glyph of Backstab",
			"Glyph of Frost Nova",
			"Glyph of Hunter's Mark",
			"Glyph of Power Word: Shield",
			"Glyph of Rejuvenation",
			"Glyph of Spiritual Attunement",
		},
		recipe = { "1x Midnight Ink, 1x Light Parchment" },
	},
	{
		min = 85,
		max = 89,
		craft = {
			"Glyph of Backstab",
			"Glyph of Frost Nova",
			"Glyph of Hunter's Mark",
			"Glyph of Power Word: Shield",
			"Glyph of Rejuvenation",
			"Glyph of Spiritual Attunement",
			"Glyph of Corruption",
			"Glyph of Flame Shock",
			"Glyph of Rapid Charge",
			"Glyph of Wrath",
		},
		recipe = { "1x Midnight Ink, 1x Light Parchment" },
	},
	{
		min = 90,
		max = 94,
		craft = {
			"Glyph of Corruption",
			"Glyph of Flame Shock",
			"Glyph of Rapid Charge",
			"Glyph of Wrath",
			"Glyph of Hammer of Justice",
			"Glyph of Ice Armor",
			"Glyph of Maul",
			"Glyph of Serpent Sting",
		},
		recipe = { "1x Midnight Ink, 1x Light Parchment" },
	},
	{
		min = 95,
		max = 99,
		craft = { "Glyph of Hammer of Justice", "Glyph of Ice Armor", "Glyph of Maul", "Glyph of Serpent Sting" },
		recipe = { "1x Midnight Ink, 1x Light Parchment" },
	},
	{ min = 100, max = 104, craft = { "Lion's Ink" }, recipe = { "2x Golden Pigment" } },
	{
		min = 105,
		max = 109,
		craft = { "Glyph of Eviscerate", "Glyph of Fade", "Glyph of Holy Light" },
		recipe = { "1x Lion's Ink, 1x Common Parchment" },
	},
	{
		min = 110,
		max = 114,
		craft = { "Glyph of Fire Nova", "Glyph of Health Funnel", "Glyph of Rending" },
		recipe = { "1x Lion's Ink, 1x Common Parchment" },
	},
	{
		min = 115,
		max = 119,
		craft = { "Glyph of Arcane Missiles", "Glyph of Healing Touch", "Glyph of Mending" },
		recipe = { "1x Lion's Ink, 1x Common Parchment" },
	},
	{
		min = 120,
		max = 124,
		craft = { "Glyph of Expose Armor", "Glyph of Flash Heal", "Glyph of Judgement" },
		recipe = { "1x Lion's Ink, 1x Common Parchment" },
	},
	{
		min = 125,
		max = 129,
		craft = {
			"Glyph of Distract",
			"Glyph of Fear",
			"Glyph of Flametongue Weapon",
			"Glyph of Frost Ward",
			"Glyph of Hamstring",
			"Glyph of Kilrogg",
			"Glyph of Vanish",
			"Glyph of Water Breathing",
		},
		recipe = { "1x Lion's Ink, 1x Common Parchment" },
	},
	{
		min = 130,
		max = 134,
		craft = { "Glyph of Blink", "Glyph of Immolation Trap", "Glyph of Moonfire" },
		recipe = { "1x Lion's Ink, 1x Common Parchment" },
	},
	{
		min = 135,
		max = 139,
		craft = { "Glyph of Divinity", "Glyph of Garrote", "Glyph of Inner Fire" },
		recipe = { "1x Lion's Ink, 1x Common Parchment" },
	},
	{
		min = 140,
		max = 149,
		craft = { "Glyph of Imp", "Glyph of Lightning Bolt", "Glyph of Sunder Armor" },
		recipe = { "1x Lion's Ink, 1x Common Parchment" },
	},
	{ min = 150, max = 154, craft = { "Jadefire Ink" }, recipe = { "2x Emerald Pigment" } },
	{
		min = 155,
		max = 159,
		craft = { "Glyph of Evocation", "Glyph of Righteous Defense" },
		recipe = { "1x Jadefire Ink, 1x Common Parchment" },
	},
	{
		min = 160,
		max = 164,
		craft = { "Glyph of Gouge", "Glyph of Renew" },
		recipe = { "1x Jadefire Ink, 1x Common Parchment" },
	},
	{
		min = 165,
		max = 169,
		craft = { "Glyph of Lava Lash", "Glyph of Shadow Bolt" },
		recipe = { "1x Jadefire Ink, 1x Common Parchment", "1x Jadefire Ink, 1x Common Parchment" },
	},
	{
		min = 170,
		max = 174,
		craft = { "Glyph of Overpower", "Glyph of Rebirth" },
		recipe = { "1x Jadefire Ink, 1x Common Parchment", "1x Jadefire Ink, 1x Common Parchment" },
	},
	{
		min = 175,
		max = 179,
		craft = { "Glyph of Aimed Shot", "Glyph of Icy Veins", "Glyph of Levitate" },
		recipe = {
			"1x Jadefire Ink, 1x Common Parchment",
			"1x Jadefire Ink, 1x Common Parchment",
			"1x Jadefire Ink, 1x Common Parchment",
		},
	},
	{
		min = 180,
		max = 184,
		craft = { "Glyph of Cleansing", "Glyph of Mind Flay" },
		recipe = { "1x Jadefire Ink, 1x Common Parchment", "1x Jadefire Ink, 1x Common Parchment" },
	},
	{
		min = 185,
		max = 189,
		craft = { "Glyph of Frost Shock", "Glyph of Sap" },
		recipe = { "1x Jadefire Ink, 1x Common Parchment", "1x Jadefire Ink, 1x Common Parchment" },
	},
	{
		min = 190,
		max = 199,
		craft = { "Glyph of Revenge", "Glyph of Voidwalker" },
		recipe = { "1x Jadefire Ink, 1x Common Parchment", "1x Jadefire Ink, 1x Common Parchment" },
	},
	{ min = 200, max = 204, craft = { "Celestial Ink" }, recipe = { "2x Violet Pigment" } },
	{ min = 205, max = 209, craft = { "Armor Vellum II" }, recipe = { "1x Celestial Ink, 2x Common Parchment" } },
	{
		min = 210,
		max = 214,
		craft = { "Glyph of Sinister Strike", "Glyph of Smite" },
		recipe = { "1x Celestial Ink, 1x Heavy Parchment", "1x Celestial Ink, 1x Heavy Parchment" },
	},
	{
		min = 215,
		max = 219,
		craft = { "Glyph of Healing Stream Totem", "Glyph of Searing Pain" },
		recipe = { "1x Celestial Ink, 1x Heavy Parchment", "1x Celestial Ink, 1x Heavy Parchment" },
	},
	{
		min = 220,
		max = 224,
		craft = { "Glyph of Barbaric Insults", "Glyph of Starfire" },
		recipe = { "1x Celestial Ink, 1x Heavy Parchment", "1x Celestial Ink, 1x Heavy Parchment" },
	},
	{
		min = 225,
		max = 229,
		craft = { "Glyph of Disengage", "Glyph of Ice Block" },
		recipe = { "1x Celestial Ink, 1x Heavy Parchment", "1x Celestial Ink, 1x Heavy Parchment" },
	},
	{
		min = 230,
		max = 234,
		craft = { "Glyph of Crusader Strike", "Glyph of Dispel Magic" },
		recipe = { "1x Celestial Ink, 1x Heavy Parchment", "1x Celestial Ink, 1x Heavy Parchment" },
	},
	{
		min = 235,
		max = 239,
		craft = { "Glyph of Lesser Healing Wave", "Glyph of Slice and Dice" },
		recipe = { "1x Celestial Ink, 1x Heavy Parchment", "1x Celestial Ink, 1x Heavy Parchment" },
	},
	{
		min = 240,
		max = 249,
		craft = { "Glyph of Cleaving", "Glyph of Soulstone" },
		recipe = { "1x Celestial Ink, 1x Heavy Parchment", "1x Celestial Ink, 1x Heavy Parchment" },
	},
	{ min = 250, max = 254, craft = { "Shimmering Ink" }, recipe = { "2x Silvery Pigment" } },
	{ min = 255, max = 259, craft = { "Scroll of Spirit V" }, recipe = { "1x Shimmering Ink, 2x Heavy Parchment" } },
	{
		min = 260,
		max = 264,
		craft = { "Glyph of Freezing Trap", "Glyph of Shred" },
		recipe = { "1x Shimmering Ink, 1x Heavy Parchment", "1x Shimmering Ink, 1x Heavy Parchment" },
	},
	{
		min = 265,
		max = 269,
		craft = { "Glyph of Bone Shield", "Glyph of Exorcism" },
		recipe = { "1x Shimmering Ink, 1x Heavy Parchment", "1x Shimmering Ink, 1x Heavy Parchment" },
	},
	{
		min = 270,
		max = 274,
		craft = { "Glyph of Fear Ward", "Glyph of Frost Strike" },
		recipe = { "1x Shimmering Ink, 1x Heavy Parchment", "1x Shimmering Ink, 1x Heavy Parchment" },
	},
	{
		min = 275,
		max = 279,
		craft = { "Glyph of Shadowburn", "Glyph of Water Mastery", "Glyph of Dark Death" },
		recipe = {
			"1x Shimmering Ink, 1x Heavy Parchment",
			"1x Shimmering Ink, 1x Heavy Parchment",
			"1x Shimmering Ink, 1x Heavy Parchment",
		},
	},
	{
		min = 280,
		max = 284,
		craft = { "Glyph of Disease", "Glyph of Icy Touch", "Glyph of Mana Gem" },
		recipe = {
			"1x Shimmering Ink, 1x Heavy Parchment",
			"1x Shimmering Ink, 1x Heavy Parchment",
			"1x Shimmering Ink, 1x Heavy Parchment",
		},
	},
	{
		min = 285,
		max = 289,
		craft = { "Glyph of Death Grip", "Glyph of Execution", "Glyph of Sprint" },
		recipe = {
			"1x Shimmering Ink, 1x Heavy Parchment",
			"1x Shimmering Ink, 1x Heavy Parchment",
			"1x Shimmering Ink, 1x Heavy Parchment",
		},
	},
	{ min = 290, max = 304, craft = { "Ethereal Ink" }, recipe = { "2x Nether Pigment" } },
	{
		min = 305,
		max = 309,
		craft = { "Glyph of Feint", "Glyph of Unbreakable Armor" },
		recipe = { "1x Ethereal Ink, 1x Heavy Parchment", "1x Ethereal Ink, 1x Resilient Parchment" },
	},
	{
		min = 310,
		max = 314,
		craft = { "Glyph of Rake", "Glyph of Rune Tap" },
		recipe = { "1x Ethereal Ink, 1x Resilient Parchment", "1x Ethereal Ink, 1x Resilient Parchment" },
	},
	{
		min = 315,
		max = 319,
		craft = { "Glyph of Arcane Blast", "Glyph of Holy Nova", "Glyph of Rapid Fire" },
		recipe = {
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
		},
	},
	{
		min = 320,
		max = 324,
		craft = { "Glyph of Blood Strike", "Glyph of Sweeping Strikes" },
		recipe = { "1x Ethereal Ink, 1x Resilient Parchment", "1x Ethereal Ink, 1x Resilient Parchment" },
	},
	{
		min = 325,
		max = 329,
		craft = {
			"Glyph of Blood Tap",
			"Glyph of Enduring Victory",
			"Glyph of Horn of Winter",
			"Glyph of Mage Armor",
			"Glyph of Succubus",
		},
		recipe = {
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
		},
	},
	{
		min = 330,
		max = 334,
		craft = { "Glyph of Scourge Strike", "Glyph of Windfury Weapon" },
		recipe = { "1x Ethereal Ink, 1x Resilient Parchment", "1x Ethereal Ink, 1x Resilient Parchment" },
	},
	{
		min = 335,
		max = 339,
		craft = { "Glyph of Arcane Power", "Glyph of Seal of Command" },
		recipe = { "1x Ethereal Ink, 1x Resilient Parchment", "1x Ethereal Ink, 1x Resilient Parchment" },
	},
	{
		min = 340,
		max = 344,
		craft = { "Glyph of Ambush", "Glyph of Death Strike" },
		recipe = { "1x Ethereal Ink, 1x Resilient Parchment", "1x Ethereal Ink, 1x Resilient Parchment" },
	},
	{
		min = 345,
		max = 349,
		craft = { "Glyph of Vampiric Blood", "Glyph of Whirlwind" },
		recipe = { "1x Ethereal Ink, 1x Resilient Parchment", "1x Ethereal Ink, 1x Resilient Parchment" },
	},
	{ min = 350, max = 354, craft = { "Ink of the Sea" }, recipe = { "2x Azure Pigment" } },
	{
		min = 355,
		max = 359,
		craft = { "Scroll of Spirit VII" },
		recipe = { "1x Ink of the Sea, 2x Resilient Parchment" },
	},
	{
		min = 360,
		max = 364,
		craft = { "Scroll of Intellect VII" },
		recipe = { "1x Ink of the Sea, 2x Resilient Parchment" },
	},
	{
		min = 365,
		max = 369,
		craft = { "Scroll of Strength VII" },
		recipe = { "1x Ink of the Sea, 2x Resilient Parchment" },
	},
	{
		min = 370,
		max = 374,
		craft = { "Scroll of Agility VII" },
		recipe = { "1x Ink of the Sea, 2x Resilient Parchment" },
	},
	{ min = 375, max = 379, craft = { "Snowfall Ink" }, recipe = { "2x Icy Pigment" } },
	{ min = 380, max = 384, craft = { "Glyph of Focus" }, recipe = { "1x Ink of the Sea, 1x Resilient Parchment" } },
	{
		min = 385,
		max = 385,
		craft = { "Northrend Inscription Research", "Glyph of Polymorph" },
		recipe = {
			"3x Ink of the Sea, 1x Snowfall Ink, 5x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
		},
	},
	{
		min = 386,
		max = 399,
		craft = {
			"Northrend Inscription Research",
			"Glyph of Polymorph",
			"Glyph of Adrenaline Rush",
			"Glyph of Lava",
			"Glyph of Anti-Magic Shell",
			"Glyph of Aspect of the Viper",
			"Glyph of Avenger's Shield",
			"Glyph of Avenging Wrath",
			"Glyph of Bestial Wrath",
			"Glyph of Blade Flurry",
			"Glyph of Blocking",
			"Glyph of Bloodthirst",
			"Glyph of Chain Heal",
			"Glyph of Chain Lightning",
			"Glyph of Chains of Ice",
			"Glyph of Circle of Healing",
			"Glyph of Conflagrate",
			"Glyph of Crippling Poison",
			"Glyph of Curse of Agony",
			"Glyph of Dark Command",
			"Glyph of Deadly Throw",
			"Glyph of Death and Decay",
			"Glyph of Death Coil",
			"Glyph of Devastate",
			"Glyph of Elemental Mastery",
			"Glyph of Felguard",
			"Glyph of Felhunter",
			"Glyph of Fire Blast",
			"Glyph of Fire Elemental Totem",
			"Glyph of Fireball",
			"Glyph of Frostbolt",
			"Glyph of Frostfire",
			"Glyph of Ghostly Strike",
			"Glyph of Growl",
			"Glyph of Hammer of Wrath",
			"Glyph of Healing Wave",
			"Glyph of Heart Strike",
			"Glyph of Hemorrhage",
			"Glyph of Holy Wrath",
			"Glyph of Howl of Terror",
			"Glyph of Hurricane",
			"Glyph of Icebound Fortitude",
			"Glyph of Immolate",
			"Glyph of Innervate",
			"Glyph of Intervene",
			"Glyph of Invisibility",
			"Glyph of Last Stand",
			"Glyph of Lifebloom",
			"Glyph of Lightwell",
			"Glyph of Mana Tide Totem",
			"Glyph of Mangle",
			"Glyph of Mass Dispel",
			"Glyph of Mind Control",
			"Glyph of Molten Armor",
			"Glyph of Mortal Strike",
			"Glyph of Obliterate",
			"Glyph of Prayer of Healing",
			"Glyph of Preparation",
			"Glyph of Regrowth",
			"Glyph of Remove Curse",
			"Glyph of Resonating Power",
			"Glyph of Rune Strike",
			"Glyph of Rupture",
			"Glyph of Seal of Light",
			"Glyph of Seal of Righteousness",
			"Glyph of Seal of Vengeance",
			"Glyph of Seal of Wisdom",
			"Glyph of Shadow",
			"Glyph of Shadow Word: Death",
			"Glyph of Shocking",
			"Glyph of Siphon Life",
			"Glyph of Snake Trap",
			"Glyph of Spirit of Redemption",
			"Glyph of Starfall",
			"Glyph of Steady Shot",
			"Glyph of Swiftmend",
			"Glyph of Taunt",
			"Glyph of the Beast",
			"Glyph of Trueshot Aura",
			"Glyph of Unstable Affliction",
			"Glyph of Victory Rush",
			"Glyph of Vigor",
			"Glyph of Volley",
			"Glyph of Water Elemental",
			"Glyph of Wyvern Sting",
		},
		recipe = {
			"3x Ink of the Sea, 1x Snowfall Ink, 5x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
		},
	},
	{
		min = 400,
		max = 404,
		craft = { "Scroll of Stamina VIII" },
		recipe = { "1x Ink of the Sea, 2x Resilient Parchment" },
	},
	{
		min = 405,
		max = 409,
		craft = { "Scroll of Spirit VIII" },
		recipe = { "1x Ink of the Sea, 2x Resilient Parchment" },
	},
	{
		min = 410,
		max = 414,
		craft = { "Scroll of Intellect VIII" },
		recipe = { "1x Ink of the Sea, 2x Resilient Parchment" },
	},
	{
		min = 415,
		max = 419,
		craft = { "Scroll of Strength VIII" },
		recipe = { "1x Ink of the Sea, 2x Resilient Parchment" },
	},
	{
		min = 420,
		max = 424,
		craft = { "Scroll of Agility VIII" },
		recipe = { "1x Ink of the Sea, 2x Resilient Parchment" },
	},
	{
		min = 425,
		max = 439,
		craft = {
			"Northrend Inscription Research",
			"Glyph of Arcane Barrage",
			"Glyph of Barkskin",
			"Glyph of Beacon of Light",
			"Glyph of Berserk",
			"Glyph of Bladestorm",
			"Glyph of Chaos Bolt",
			"Glyph of Chimera Shot",
			"Glyph of Cloak of Shadows",
			"Glyph of Dancing Rune Weapon",
			"Glyph of Deep Freeze",
			"Glyph of Demonic Circle",
			"Glyph of Dispersion",
			"Glyph of Divine Plea",
			"Glyph of Divine Storm",
			"Glyph of Enraged Regeneration",
			"Glyph of Explosive Shot",
			"Glyph of Explosive Trap",
			"Glyph of Fan of Knives",
			"Glyph of Feral Spirit",
			"Glyph of Guardian Spirit",
			"Glyph of Hammer of the Righteous",
			"Glyph of Haunt",
			"Glyph of Hex",
			"Glyph of Holy Shock",
			"Glyph of Howling Blast",
			"Glyph of Hunger for Blood",
			"Glyph of Hungering Cold",
			"Glyph of Hymn of Hope",
			"Glyph of Ice Barrier",
			"Glyph of Kill Shot",
			"Glyph of Killing Spree",
			"Glyph of Life Tap",
			"Glyph of Living Bomb",
			"Glyph of Metamorphosis",
			"Glyph of Mind Sear",
			"Glyph of Mirror Image",
			"Glyph of Nourish",
			"Glyph of Penance",
			"Glyph of Raptor Strike",
			"Glyph of Riptide",
			"Glyph of Salvation",
			"Glyph of Savage Roar",
			"Glyph of Scatter Shot",
			"Glyph of Shadow Dance",
			"Glyph of Shadowflame",
			"Glyph of Shield of Righteousness",
			"Glyph of Shield Wall",
			"Glyph of Shockwave",
			"Glyph of Soul Link",
			"Glyph of Spell Reflection",
			"Glyph of Stoneclaw Totem",
			"Glyph of Survival Instincts",
			"Glyph of Thunder",
			"Glyph of Tricks of the Trade",
			"Glyph of Unholy Blight",
			"Glyph of Vigilance",
			"Glyph of Wild Growth",
		},
		recipe = {
			"3x Ink of the Sea, 1x Snowfall Ink, 5x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Celestial Ink, 1x Heavy Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Jadefire Ink, 1x Common Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Celestial Ink, 1x Common Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Celestial Ink, 1x Heavy Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Midnight Ink, 1x Light Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Midnight Ink, 1x Light Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Lion's Ink, 1x Common Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Lion's Ink, 1x Light Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Lion's Ink, 1x Common Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Lion's Ink, 1x Light Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Midnight Ink, 1x Light Parchment",
			"1x Ink of the Sea, 1x Light Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Ink of the Sea, 1x Resilient Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
			"1x Celestial Ink, 1x Common Parchment",
			"1x Ethereal Ink, 1x Resilient Parchment",
		},
	},
	{
		min = 440,
		max = 449,
		craft = { "Runescroll of Fortitude", "Northrend Inscription Research" },
		recipe = {
			"1x Snowfall Ink, 5x Resilient Parchment",
			"3x Ink of the Sea, 1x Snowfall Ink, 5x Resilient Parchment",
		},
	},
}

addonTable.getInscription = function(rank)
	for _, data in ipairs(craftingData) do
		if rank >= data.min and rank <= data.max then
			return data.craft, data.recipe
		end
	end
	return nil, nil -- Return nil if no match is found
end
