local addonName, addonTable = ...

local craftingData = {
	{
		min = 1,
		max = 29,
		craft = { "Тонкая медная проволока" },
		recipe = { "2x Медный слиток" },
	},
	{
		min = 30,
		max = 49,
		craft = { "Кольцо с тигровым глазом", "Малахитовая подвеска" },
		recipe = {
			"1x Тигровый глаз, 1x Тонкая медная проволока",
			"1x Малахит, 1x Тонкая медная проволока",
		},
	},
	{
		min = 50,
		max = 79,
		craft = {
			"Bronze Setting",
			"Кольцо с тигровым глазом",
			"Малахитовая подвеска",
		},
		recipe = {
			"2x Bronze Bar",
			"1x Тигровый глаз, 1x Тонкая медная проволока",
			"1x Малахит, 1x Тонкая медная проволока",
		},
	},
	{
		min = 80,
		max = 99,
		craft = { "Ring of Silver Might", "Gloom Band", "Simple Pearl Ring" },
		recipe = {
			"2x Silver Bar",
			"1x Bronze Setting, 2x Shadowgem, 2x Тонкая медная проволока",
			"1x Small Lustrous Pearl, 1x Bronze Setting, 2x Copper Bar",
		},
	},
	{
		min = 100,
		max = 109,
		craft = { "Ring of Twilight Shadows", "Ring of Silver Might", "Gloom Band", "Simple Pearl Ring" },
		recipe = {
			"2x Shadowgem, 2x Bronze Bar",
			"2x Silver Bar",
			"1x Bronze Setting, 2x Shadowgem, 2x Тонкая медная проволока",
			"1x Small Lustrous Pearl, 1x Bronze Setting, 2x Copper Bar",
		},
	},
	{
		min = 110,
		max = 119,
		craft = { "Heavy Stone Statue", "Ring of Twilight Shadows", "Ring of Silver Might" },
		recipe = { "8x Heavy Stone", "2x Shadowgem, 2x Bronze Bar", "2x Silver Bar" },
	},
	{
		min = 120,
		max = 149,
		craft = { "Pendant of the Agate Shield", "Heavy Stone Statue", "Ring of Twilight Shadows" },
		recipe = { "1x Moss Agate, 1x Bronze Setting", "8x Heavy Stone", "2x Shadowgem, 2x Bronze Bar" },
	},
	{ min = 150, max = 179, craft = { "Mithril Filigree" }, recipe = { "2x Mithril Bar" } },
	{
		min = 180,
		max = 199,
		craft = { "Engraved Truesilver Ring" },
		recipe = { "1x Truesilver Bar, 2x Mithril Filigree" },
	},
	{ min = 200, max = 219, craft = { "Citrine Ring of Rapid Healing" }, recipe = { "1x Citrine, 2x Mithril Bar" } },
	{
		min = 220,
		max = 224,
		craft = { "Aquamarine Pendant of the Warrior", "Citrine Ring of Rapid Healing" },
		recipe = { "1x Aquamarine, 3x Mithril Filigree", "1x Citrine, 2x Mithril Bar" },
	},
	{ min = 225, max = 244, craft = { "Thorium Setting" }, recipe = { "1x Thorium Bar" } },
	{ min = 245, max = 259, craft = { "Ruby Pendant of Fire" }, recipe = { "1x Star Ruby, 1x Thorium Setting" } },
	{ min = 260, max = 279, craft = { "Simple Opal Ring" }, recipe = { "1x Large Opal, 1x Thorium Setting" } },
	{
		min = 280,
		max = 289,
		craft = { "Glowing Thorium Band", "Sapphire Pendant of Winter Night", "Onslaught Ring" },
		recipe = {
			"2x Azerothian Diamond",
			"1x Blue Sapphire, 1x Essence of Undeath, 1x Thorium Setting",
			"1x Powerful Mojo, 1x Essence of Earth, 1x Thorium Setting",
		},
	},
	{
		min = 290,
		max = 299,
		craft = { "Emerald Lion Ring", "Glowing Thorium Band", "Sapphire Pendant of Winter Night", "Onslaught Ring" },
		recipe = {
			"2x Huge Emerald, 1x Thorium Setting",
			"2x Azerothian Diamond",
			"1x Blue Sapphire, 1x Essence of Undeath, 1x Thorium Setting",
			"1x Powerful Mojo, 1x Essence of Earth, 1x Thorium Setting",
		},
	},
	{
		min = 300,
		max = 319,
		craft = {
			"Teardrop Blood Garnet",
			"Brilliant Golden Draenite",
			"Solid Azure Moonstone",
			"Radiant Deep Peridot",
			"Inscribed Flame Spessarite",
			"Glowing Shadow Draenite",
			"Prismatic Black Diamond",
		},
		recipe = {
			"1x Blood Garnet",
			"1x Golden Draenite",
			"1x Azure Moonstone",
			"1x Deep Peridot",
			"1x Flame Spessarite",
			"1x Shadow Draenite",
			"1x Black Diamond",
		},
	},
	{
		min = 320,
		max = 324,
		craft = {
			"Bold Blood Garnet",
			"Bright Blood Garnet",
			"Jagged Deep Peridot",
			"Sparkling Azure Moonstone",
			"Gleaming Golden Draenite",
			"Luminous Flame Spessarite",
			"Royal Shadow Draenite",
			"",
		},
		recipe = {
			"1x Blood Garnet",
			"1x Blood Garnet",
			"1x Deep Peridot",
			"1x Azure Moonstone",
			"1x Golden Draenite",
			"1x Flame Spessarite",
			"1x Shadow Draenite",
		},
	},
	{
		min = 325,
		max = 339,
		craft = {
			"Mercurial Adamantite",
			"Rigid Golden Draenite",
			"Smooth Golden Draenite",
			"Sovereign Shadow Draenite",
			"Dazzling Deep Peridot",
			"Delicate Blood Garnet",
			"Potent Flame Spessarite",
			"Great Golden Draenite",
			"Balanced Shadow Draenite",
			"Infused Shadow Draenite",
			"Lustrous Azure Moonstone",
			"Veiled Flame Spessarite",
			"Wicked Flame Spessarite",
		},
		recipe = {
			"4x Adamantite Powder, 1x Primal Earth",
			"1x Golden Draenite",
			"1x Golden Draenite",
			"1x Shadow Draenite",
			"1x Deep Peridot",
			"1x Blood Garnet",
			"1x Flame Spessarite",
			"1x Golden Draenite",
			"1x Shadow Draenite",
			"1x Shadow Draenite",
			"1x Azure Moonstone",
			"1x Flame Spessarite",
			"1x Flame Spessarite",
		},
	},
	{
		min = 340,
		max = 349,
		craft = {
			"Heavy Adamantite Ring",
			"Rigid Golden Draenite",
			"Smooth Golden Draenite",
			"Sovereign Shadow Draenite",
			"Dazzling Deep Peridot",
			"Delicate Blood Garnet",
			"Potent Flame Spessarite",
			"Great Golden Draenite",
			"Balanced Shadow Draenite",
			"Infused Shadow Draenite",
			"Lustrous Azure Moonstone",
			"Veiled Flame Spessarite",
			"Wicked Flame Spessarite",
		},
		recipe = {
			"1x Adamantite Bar, 1x Mercurial Adamantite",
			"1x Golden Draenite",
			"1x Golden Draenite",
			"1x Shadow Draenite",
			"1x Deep Peridot",
			"1x Blood Garnet",
			"1x Flame Spessarite",
			"1x Golden Draenite",
			"1x Shadow Draenite",
			"1x Shadow Draenite",
			"1x Azure Moonstone",
			"1x Flame Spessarite",
			"1x Flame Spessarite",
		},
	},
	{
		min = 350,
		max = 394,
		craft = {
			"Bold Bloodstone",
			"Bright Bloodstone",
			"Delicate Bloodstone",
			"Flashing Bloodstone",
			"Fractured Bloodstone",
			"Precise Bloodstone",
			"Runed Bloodstone",
			"Subtle Bloodstone",
			"Lustrous Chalcedony",
			"Solid Chalcedony",
			"Sparkling Chalcedony",
			"Stormy Chalcedony",
			"Dazzling Dark Jade",
			"Enduring Dark Jade",
			"Energized Dark Jade",
			"Forceful Dark Jade",
			"Intricate Dark Jade",
			"Jagged Dark Jade",
			"Lambent Dark Jade",
			"Misty Dark Jade",
			"Opaque Dark Jade",
			"Radiant Dark Jade",
			"Seer's Dark Jade",
			"Shattered Dark Jade",
			"Shining Dark Jade",
			"Steady Dark Jade",
			"Sundered Dark Jade",
			"Tense Dark Jade",
			"Timeless Dark Jade",
			"Turbid Dark Jade",
			"Vivid Dark Jade",
			"Accurate Huge Citrine",
			"Champion's Huge Citrine",
			"Deadly Huge Citrine",
			"Deft Huge Citrine",
			"Durable Huge Citrine",
			"Empowered Huge Citrine",
			"Etched Huge Citrine",
			"Fierce Huge Citrine",
			"Glimmering Huge Citrine",
			"Glinting Huge Citrine",
			"Inscribed Huge Citrine",
			"Lucent Huge Citrine",
			"Luminous Huge Citrine",
			"Potent Huge Citrine",
			"Pristine Huge Citrine",
			"Reckless Huge Citrine",
			"Resolute Huge Citrine",
			"Resplendent Huge Citrine",
			"Stalwart Huge Citrine",
			"Stark Huge Citrine",
			"Veiled Huge Citrine",
			"Wicked Huge Citrine",
			"Balanced Shadow Crystal",
			"Defender's Shadow Crystal",
			"Glowing Shadow Crystal",
			"Guardian's Shadow Crystal",
			"Infused Shadow Crystal",
			"Mysterious Shadow Crystal",
			"Puissant Shadow Crystal",
			"Purified Shadow Crystal",
			"Regal Shadow Crystal",
			"Royal Shadow Crystal",
			"Shifting Shadow Crystal",
			"Sovereign Shadow Crystal",
			"Tenuous Shadow Crystal",
			"Brilliant Sun Crystal",
			"Mystic Sun Crystal",
			"Quick Sun Crystal",
			"Rigid Sun Crystal",
			"Smooth Sun Crystal",
			"Thick Sun Crystal",
		},
		recipe = {
			"1x Bloodstone",
			"1x Bloodstone",
			"1x Bloodstone",
			"1x Bloodstone",
			"1x Bloodstone",
			"1x Bloodstone",
			"1x Bloodstone",
			"1x Bloodstone",
			"1x Chalcedony",
			"1x Chalcedony",
			"1x Chalcedony",
			"1x Chalcedony",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Dark Jade",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Huge Citrine",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Shadow Crystal",
			"1x Sun Crystal",
			"1x Sun Crystal",
			"1x Sun Crystal",
			"1x Sun Crystal",
			"1x Sun Crystal",
			"1x Sun Crystal",
		},
	},
	{
		min = 395,
		max = 399,
		craft = { "Bloodstone Band", "Crystal Chalcedony Amulet", "Crystal Citrine Necklace", "Sun Rock Ring" },
		recipe = {
			"1x Bloodstone, 2x Crystallized Earth",
			"1x Chalcedony, 2x Crystallized Earth",
			"1x Huge Citrine, 2x Crystallized Earth",
			"1x Sun Crystal, 2x Crystallized Earth",
		},
	},
	{
		min = 420,
		max = 424,
		craft = {
			"Dazzling Forest Emerald",
			"Balanced Twilight Opal",
			"Bright Scarlet Ruby",
			"Brilliant Autumn's Glow",
			"Pristine Monarch Topaz",
			"Sparkling Sky Sapphire",
			"Enchanted Tear",
		},
		recipe = {
			"1x Forest Emerald",
			"1x Twilight Opal",
			"1x Scarlet Ruby",
			"1x Autumn's Glow",
			"1x Monarch Topaz",
			"1x Sky Sapphire",
			"1x Siren's Tear, 4x Infinite Dust",
		},
	},
	{
		min = 425,
		max = 449,
		craft = {
			"Swift Skyflare Diamond",
			"Tireless Skyflare Diamond",
			"Chaotic Skyflare Diamond",
			"Destructive Skyflare Diamond",
			"Effulgent Skyflare Diamond",
			"Ember Skyflare Diamond",
			"Enigmatic Skyflare Diamond",
			"Forlorn Skyflare Diamond",
			"Impassive Skyflare Diamond",
			"Revitalizing Skyflare Diamond",
			"Thundering Skyflare Diamond",
			"Persistent Earthsiege Diamond",
			"Powerful Earthsiege Diamond",
			"Austere Earthsiege Diamond",
			"Beaming Earthsiege Diamond",
			"Bracing Earthsiege Diamond",
			"Eternal Earthsiege Diamond",
			"Insightful Earthsiege Diamond",
			"Invigorating Earthsiege Diamond",
			"Relentless Earthsiege Diamond",
			"Trenchant Earthsiege Diamond",
		},
		recipe = {
			"1x Skyflare Diamond",
			"1x Skyflare Diamond",
			"1x Skyflare Diamond",
			"1x Skyflare Diamond",
			"1x Skyflare Diamond",
			"1x Skyflare Diamond",
			"1x Skyflare Diamond",
			"1x Skyflare Diamond",
			"1x Skyflare Diamond",
			"1x Skyflare Diamond",
			"1x Skyflare Diamond",
			"1x Earthsiege Diamond",
			"1x Earthsiege Diamond",
			"1x Earthsiege Diamond",
			"1x Earthsiege Diamond",
			"1x Earthsiege Diamond",
			"1x Earthsiege Diamond",
			"1x Earthsiege Diamond",
			"1x Earthsiege Diamond",
			"1x Earthsiege Diamond",
			"1x Earthsiege Diamond",
		},
	},
}

addonTable.getJewelcrafting = function(rank)
	for _, data in ipairs(craftingData) do
		if rank >= data.min and rank <= data.max then
			return data.craft, data.recipe
		end
	end
	return nil, nil -- Return nil if no match is found
end
